/*
 * City centers, from "City Center Information for Flyer Generator.xlsx"
 * (City Center Info sheet). Picking a center fills the flyer's link, email and
 * registration QR link; coordinators can still edit them. Add or fix a center here.
 */
export const CENTERS = [
  { id: "atlanta", name: "Atlanta", link: "isha.co/atlanta", email: "atlanta@ishausa.org", rsvp: "isha.co/atlanta-free-sessions" },
  { id: "austin", name: "Austin", link: "isha.co/austin", email: "austin@ishausa.org", rsvp: "isha.co/austin-free-sessions" },
  { id: "boston", name: "Boston", link: "isha.co/boston", email: "boston@ishausa.org", rsvp: "isha.co/boston-free-sessions" },
  { id: "calgary", name: "Calgary", link: "isha.co/calgary", email: "calgary@ishausa.org", rsvp: "isha.co/calgary-free-sessions" },
  { id: "charlotte", name: "Charlotte", link: "isha.co/charlotte", email: "charlotte@ishausa.org", rsvp: "isha.co/charlotte-free-sessions" },
  { id: "chicago", name: "Chicago", link: "isha.co/chicago", email: "chicago@ishausa.org", rsvp: "isha.co/chicago-free-sessions" },
  { id: "cincinnati", name: "Cincinnati", link: "isha.co/cincinnati", email: "cincinnati@ishausa.org", rsvp: "isha.co/cincinnati-free-sessions" },
  { id: "cleveland", name: "Cleveland", link: "isha.co/cleveland", email: "cleveland@ishausa.org", rsvp: "isha.co/cleveland-free-sessions" },
  { id: "columbus", name: "Columbus", link: "isha.co/columbus", email: "columbus@ishausa.org", rsvp: "isha.co/columbus-free-sessions" },
  { id: "connecticut", name: "Connecticut", link: "isha.co/connecticut", email: "connecticut@ishausa.org", rsvp: "isha.co/connecticut-free-sessions" },
  { id: "dallas", name: "Dallas", link: "isha.co/dallas", email: "dallas@ishausa.org", rsvp: "isha.co/dallas-free-sessions" },
  { id: "dayton", name: "Dayton", link: "isha.co/dayton", email: "dayton@ishausa.org", rsvp: "isha.co/dayton-free-sessions" },
  { id: "delaware", name: "Delaware", link: "isha.co/delaware", email: "delaware@ishausa.org", rsvp: "isha.co/delaware-free-sessions" },
  { id: "denver", name: "Denver", link: "isha.co/denver", email: "denver@ishausa.org", rsvp: "isha.co/denver-free-sessions" },
  { id: "detroit", name: "Detroit", link: "isha.co/detroit", email: "detroit@ishausa.org", rsvp: "isha.co/detroit-free-sessions" },
  { id: "edmonton", name: "Edmonton", link: "isha.co/edmonton", email: "edmonton@ishausa.org", rsvp: "isha.co/edmonton-free-sessions" },
  { id: "houston", name: "Houston", link: "isha.co/houston", email: "houston@ishausa.org", rsvp: "isha.co/houston-free-sessions" },
  { id: "indianapolis", name: "Indianapolis", link: "isha.co/indianapolis", email: "indianapolis@ishausa.org", rsvp: "isha.co/indianapolis-free-sessions" },
  { id: "kansascity", name: "Kansas City", link: "isha.co/kansascity", email: "kansascity@ishausa.org", rsvp: "isha.co/kansascity-free-sessions" },
  { id: "losangeles", name: "Los Angeles", link: "isha.co/losangeles", email: "losangeles@ishausa.org", rsvp: "isha.co/losangeles-free-sessions" },
  { id: "louisville", name: "Louisville", link: "isha.co/louisville", email: "louisville@ishausa.org", rsvp: "isha.co/louisville-free-sessions" },
  { id: "maryland", name: "Maryland", link: "isha.co/maryland", email: "maryland@ishausa.org", rsvp: "isha.co/maryland-free-sessions" },
  { id: "mcminnville", name: "McMinnville", link: "isha.co/mcminnville", email: "mcminnville@ishausa.org", rsvp: "isha.co/mcminnville-free-sessions" },
  { id: "memphis", name: "Memphis", link: "isha.co/memphis", email: "memphis@ishausa.org", rsvp: "isha.co/memphis-free-sessions" },
  { id: "milwaukee", name: "Milwaukee", link: "isha.co/milwaukee", email: "milwaukee@ishausa.org", rsvp: "isha.co/milwaukee-free-sessions" },
  { id: "minneapolis", name: "Minneapolis", link: "isha.co/minneapolis", email: "minneapolis@ishausa.org", rsvp: "isha.co/minneapolis-free-sessions" },
  { id: "montana", name: "Montana", link: "isha.co/montana", email: "montana@ishausa.org", rsvp: "isha.co/montana-free-sessions" },
  { id: "montreal", name: "Montreal", link: "isha.co/montreal", email: "montreal@ishausa.org", rsvp: "isha.co/montreal-free-sessions" },
  { id: "nashville", name: "Nashville", link: "isha.co/nashville", email: "nashville@ishausa.org", rsvp: "isha.co/nashville-free-sessions" },
  { id: "newjersey", name: "New Jersey", link: "isha.co/newjersey", email: "newjersey@ishausa.org", rsvp: "isha.co/newjersey-free-sessions" },
  { id: "newyork", name: "New York", link: "isha.co/newyork", email: "newyork@ishausa.org", rsvp: "isha.co/newyork-free-sessions" },
  { id: "orangecounty", name: "Orange County", link: "isha.co/orangecounty", email: "orangecounty@ishausa.org", rsvp: "isha.co/orangecounty-free-sessions" },
  { id: "orlando", name: "Orlando", link: "isha.co/orlando", email: "orlando@ishausa.org", rsvp: "isha.co/orlando-free-sessions" },
  { id: "ottawa", name: "Ottawa", link: "isha.co/ottawa", email: "ottawa@ishausa.org", rsvp: "isha.co/ottawa-free-sessions" },
  { id: "philadelphia", name: "Philadelphia", link: "isha.co/philadelphia", email: "philadelphia@ishausa.org", rsvp: "isha.co/philadelphia-free-sessions" },
  { id: "phoenix", name: "Phoenix", link: "isha.co/phoenix", email: "phoenix@ishausa.org", rsvp: "isha.co/phoenix-free-sessions" },
  { id: "pittsburgh", name: "Pittsburgh", link: "isha.co/pittsburgh", email: "pittsburgh@ishausa.org", rsvp: "isha.co/pittsburgh-free-sessions" },
  { id: "portland", name: "Portland", link: "isha.co/portland", email: "portland@ishausa.org", rsvp: "isha.co/portland-free-sessions" },
  { id: "raleigh", name: "Raleigh", link: "isha.co/raleigh", email: "raleigh@ishausa.org", rsvp: "isha.co/raleigh-free-sessions" },
  { id: "regina", name: "Regina", link: "isha.co/regina", email: "regina@ishausa.org", rsvp: "isha.co/regina-free-sessions" },
  { id: "richmond", name: "Richmond", link: "isha.co/richmond", email: "richmond@ishausa.org", rsvp: "isha.co/richmond-free-sessions" },
  { id: "rochester", name: "Rochester", link: "isha.co/rochester", email: "rochester@ishausa.org", rsvp: "isha.co/rochester-free-sessions" },
  { id: "sacramento", name: "Sacramento", link: "isha.co/sacramento", email: "sacramento@ishausa.org", rsvp: "isha.co/sacramento-free-sessions" },
  { id: "saltlakecity", name: "Salt Lake City", link: "isha.co/saltlakecity", email: "saltlakecity@ishausa.org", rsvp: "isha.co/saltlakecity-free-sessions" },
  { id: "sanantonio", name: "San Antonio", link: "isha.co/sanantonio", email: "sanantonio@ishausa.org", rsvp: "isha.co/sanantonio-free-sessions" },
  { id: "sandiego", name: "San Diego", link: "isha.co/sandiego", email: "sandiego@ishausa.org", rsvp: "isha.co/sandiego-free-sessions" },
  { id: "sfcity", name: "San Francisco (City)", link: "isha.co/sfcity", email: "sfcity@ishausa.org", rsvp: "isha.co/sfcity-free-sessions" },
  { id: "santabarbara", name: "Santa Barbara", link: "isha.co/santabarbara", email: "santabarbara@ishausa.org", rsvp: "isha.co/santabarbara-free-sessions" },
  { id: "santafe", name: "Santa Fe", link: "isha.co/santafe", email: "santafe@ishausa.org", rsvp: "isha.co/santafe-free-sessions" },
  { id: "sarasota", name: "Sarasota", link: "isha.co/sarasota", email: "sarasota@ishausa.org", rsvp: "isha.co/sarasota-free-sessions" },
  { id: "seattle", name: "Seattle", link: "isha.co/seattle", email: "seattle@ishausa.org", rsvp: "isha.co/seattle-free-sessions" },
  { id: "sfbay", name: "SF Bay Area", link: "isha.co/sfbay", email: "sfbay@ishausa.org", rsvp: "isha.co/sfbay-free-sessions" },
  { id: "sfeastbay", name: "SF East Bay", link: "isha.co/sfeastbay", email: "sfeastbay@ishausa.org", rsvp: "isha.co/sfeastbay-free-sessions" },
  { id: "sfsouthbay", name: "SF South Bay", link: "isha.co/sfsouthbay", email: "sfsouthbay@ishausa.org", rsvp: "isha.co/sfsouthbay-free-sessions" },
  { id: "stlouis", name: "St. Louis", link: "isha.co/stlouis", email: "stlouis@ishausa.org", rsvp: "isha.co/stlouis-free-sessions" },
  { id: "tampa", name: "Tampa", link: "isha.co/tampa", email: "tampa@ishausa.org", rsvp: "isha.co/tampa-free-sessions" },
  { id: "toronto", name: "Toronto", link: "isha.co/toronto", email: "toronto@ishausa.org", rsvp: "isha.co/toronto-free-sessions" },
  { id: "trinidadandtobago", name: "Trinidad and Tobago", link: "isha.co/trinidadandtobago", email: "trinidadandtobago@ishausa.org", rsvp: "isha.co/trinidadandtobago-free-sessions" },
  { id: "vancouver", name: "Vancouver", link: "isha.co/vancouver", email: "vancouver@ishausa.org", rsvp: "isha.co/vancouver-free-sessions" },
  { id: "washingtondc", name: "Washington DC", link: "isha.co/washingtondc", email: "washingtondc@ishausa.org", rsvp: "isha.co/washingtondc-free-sessions" },
  { id: "westpalmbeach", name: "West Palm Beach", link: "isha.co/westpalmbeach", email: "westpalmbeach@ishausa.org", rsvp: "isha.co/westpalmbeach-free-sessions" },
  { id: "wilmington", name: "Wilmington", link: "isha.co/wilmington", email: "wilmington@ishausa.org", rsvp: "isha.co/wilmington-free-sessions" }
];
